# TrainConfig
grad_from_block: 11
learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0001
epochs: 2
warmup_teacher_temp_epochs: 1
n_views: 2
warmup_teacher_temp: 0.07
teacher_temp: 0.04
memax_weight: 2.0
output_dir: "./saves"
logging_steps: 10
logging_dir: "./logs"
per_device_train_batch_size: 128
per_device_eval_batch_size: 256

# DatasetConfig
dataset: "CIFAR10"
num_workers: 2
ssb_ratio: 0.5
ssb_num_labels: null
use_ssb_splits: false
pkl_path: "data/ssb_splits/cub_osr_splits.pkl"
pkl_info_path: "data/ssb_splits/cub_osr_splits.yaml"
